server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/athletecoach_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.try-it-out-enabled=true

app.jwt-secret=athletecoach-secret-key-2026-make-this-long
app.jwt-expiration=86400000