server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/athletecoach_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.try-it-out-enabled=true
app.jwt-secret=${APP_JWT_SECRET:athletecoach-secret-key-2026-make-this-long}
app.jwt-expiration=${APP_JWT_EXPIRATION:86400000}





spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
s