INSERT IGNORE INTO drill (name, sport, target_weakness, duration_minutes, intensity, description) VALUES
('Footwork Against Spin', 'CRICKET', 'WEAK_VS_SPIN', 45, 'HIGH', 'Practice front and back foot movement against spin bowling'),
('Sweep Shot Drill', 'CRICKET', 'WEAK_VS_SPIN', 40, 'MEDIUM', 'Practice sweep and reverse sweep shots'),
('Yorker Defense Net', 'CRICKET', 'WEAK_VS_YORKER', 45, 'HIGH', 'Face yorker deliveries in nets'),
('Crease Movement Drill', 'CRICKET', 'WEAK_VS_YORKER', 35, 'MEDIUM', 'Practice moving inside crease for yorkers'),
('Short Ball Pullshot', 'CRICKET', 'WEAK_VS_PACE', 40, 'HIGH', 'Practice pull and hook shots against short balls'),
('Running Between Wickets', 'CRICKET', 'POOR_RUNNING', 30, 'MEDIUM', 'Sprint and communication drills between wickets'),
('Crease Marking Drill', 'CRICKET', 'NO_BALL_HABIT', 30, 'LOW', 'Mark crease and practice approach run'),
('Target Cone Bowling', 'CRICKET', 'WIDE_LINE_BOWLING', 40, 'MEDIUM', 'Bowl at target cones to fix line'),
('Slip Cordon Catching', 'CRICKET', 'POOR_CATCHING', 35, 'MEDIUM', 'Practice catching in slip cordon'),
('Ladder Agility Drill', 'CRICKET', 'POOR_FOOTWORK', 30, 'HIGH', 'Use ladder for foot speed and agility'),
('Target Shooting Drill', 'FOOTBALL', 'POOR_FINISHING', 45, 'HIGH', 'Shoot at targets from different angles'),
('Weak Foot Practice', 'FOOTBALL', 'WEAK_LEFT_FOOT', 40, 'MEDIUM', 'Practice passing and shooting with weak foot'),
('Heading Practice', 'FOOTBALL', 'POOR_HEADING', 35, 'MEDIUM', 'Practice heading from crosses'),
('Passing Accuracy Drill', 'FOOTBALL', 'POOR_PASSING', 40, 'MEDIUM', 'Short and long passing accuracy drills'),
('Defensive Positioning', 'FOOTBALL', 'POOR_DEFENDING', 45, 'HIGH', 'Practice defensive shape and positioning'),
('Ball Control Dribbling', 'FOOTBALL', 'POOR_DRIBBLING', 40, 'HIGH', 'Cone dribbling and ball control drills'),
('Backhand Net Practice', 'BADMINTON', 'WEAK_BACKHAND', 40, 'HIGH', 'Practice backhand strokes at net'),
('Smash Power Drill', 'BADMINTON', 'POOR_SMASH', 45, 'HIGH', 'Practice overhead smash technique'),
('Net Play Drill', 'BADMINTON', 'WEAK_NET_PLAY', 35, 'MEDIUM', 'Practice net kills and lifts'),
('Court Movement Drill', 'BADMINTON', 'POOR_FOOTWORK_BADMINTON', 40, 'HIGH', 'Full court movement and recovery'),
('Endurance Running', 'BADMINTON', 'LOW_STAMINA', 45, 'HIGH', 'Long distance running for stamina'),
('Serve Practice', 'TENNIS', 'POOR_SERVE', 45, 'HIGH', 'Practice flat and slice serves'),
('Volley Drill', 'TENNIS', 'WEAK_VOLLEY', 40, 'MEDIUM', 'Practice volleys at net'),
('Baseline Rally Drill', 'TENNIS', 'POOR_BASELINE', 45, 'HIGH', 'Practice baseline groundstrokes'),
('Backhand Slice Drill', 'TENNIS', 'WEAK_BACKHAND_TENNIS', 40, 'MEDIUM', 'Practice backhand slice and topspin'),
('Shooting Drills', 'BASKETBALL', 'WEAK_FREE_THROW', 40, 'MEDIUM', 'Practice free throws and mid range shots'),
('Dribbling Course', 'BASKETBALL', 'POOR_DRIBBLING_BASKETBALL', 35, 'HIGH', 'Cone dribbling course drills'),
('Defensive Footwork', 'BASKETBALL', 'POOR_DEFENSE', 40, 'HIGH', 'Defensive slide and positioning drills'),
('Box Out Rebounding', 'BASKETBALL', 'POOR_REBOUNDING', 35, 'MEDIUM', 'Practice boxing out and rebounding');